config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users
#   resources :courses
#   root 'home#index'
#   # get 'static_pages/landing_page'
#   # get 'static_pages/privacy_policy'
#   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

# end
Rails.application.routes.draw do
  devise_for :users
  #  do
  # get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  resources :courses
  get 'home/index'
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    validates :title,  presence: true
    validates :description, presence: true, length: { :minimum => 5} 

    belongs_to :user
    def to_s
        title
    end
    extend FriendlyId
    friendly_id :title, use: :slugged

    friendly_id :generated_slug, use: :slugged
   # # URLlink random number
    # def generated_slug
    #     require 'securerandom'
    #     @random_slug ||= persisted? ? friendly_id : SecureRandom.hex(4)
    # end
    # def to_s
    #     slug
    # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def to_s
    email
  end
  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    if params[:title]
      # Search title
      @courses = Course.where('title LIKE ?', "%#{params[:title]}%") #case-insensitive
    else
      @courses = Course.all
    end
  end
  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    # tu dong them gmail nguoi dung vao cot 
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @courses = Course.all.limit(3)
    @latest_couses = Course.all.limit(3).order(created_at: :desc)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing_page
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/courses/_course.html.haml
.card
    .card-header
        .fa.fa-book
        = link_to course.title, course_path(course)
    .card-body 
        = course.description
    .card-footer
        .far.fa-clock       
        = course.created_at.strftime('%d-%b-%Y')
        .row
        .fa.fa-chalkboard-teacher
        = course.user
    .card-footer
        = link_to 'Show', course , class: 'btn btn-sm btn-primary'
        = link_to 'Edit', edit_course_path(course) , class: 'btn btn-sm btn-warning'
        = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-sm btn-danger'

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :description

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
%h1 Editing course
.alert.alert-primary{:role => "alert"}
  This is a primary alert—check it out!

= render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
-# %h1 Listing courses

-# .card-columns
-#   - @courses.each do |course|
-#     = render 'courses/course' , course: course
-# %br
.card
  .card-header
    %h1 Editing course
  .card-body
    = render 'form'

app/views/courses/new.html.haml
.card
  .card-header
    %h1 New course
  .card-body
    = render 'form'

app/views/courses/show.html.haml
= link_to 'Courses/course', course: @course
\/
= link_to @course.title, course_path(@course)
= render 'courses/course', course: @course



-# %p#notice= notice

-# -# %p
-# -#   %b Title:
-# -#   = @course.title
-# -# %p
-# -#   %b Description:
-# -#   = @course.description

-# = link_to 'Edit', edit_course_path(@course)
-# \|

app/views/home/index.html.haml
.jumbotron
  .display-4
    What do you want to learn today?

  .p-4
  .form-inline.my-2.my-lg-0
    = form_tag(courses_path, method: :get) do
      .input-group
        = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
        %span.input-group-append
          %button.btn.btn-primary.btn-sm{:type => "submit"}
            %span.fa.fa-search{"aria-hidden" => "true"}
.card-group
  .card.card-body
    %h1
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h1
      .fa.fa-chalkboard-teacher
      /.fa.fa-brain
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h1
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h1
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule

%hr
%h2
  Popular courses
.card-columns
  - @courses.each do |course|
    = render 'courses/course', course: course

%hr
%h2 
  Top rated courses
.card-columns
  - @courses.each do |course|
    = render 'courses/course', course: course

%hr
%h2 
  Latest courses
.card-columns
  - @latest_couses.each do |course|
    = render 'courses/course', course: course

%hr

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "/"} Rubygems
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-book
            Courses
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            New Course
      .form-inline.my-2.my-lg-0
        = form_tag(courses_path, method: :get) do
          .input-group
            = text_field_tag :title, params[:title], autocomplete: 'off', placeholder: "Search", class: 'form-control-sm'
            %span.input-group-append
              %button.btn.btn-primary.btn-sm{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Another link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}" 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RubyStudy
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = render 'layouts/messages'
    .container
      = yield

app/views/static_pages/landing_page.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %a.navbar-brand{:href => "#"}
      %i.fa-solid.fa-house>
      Navbar
    %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarSupportedContent.collapse.navbar-collapse
      %ul.navbar-nav.me-auto.mb-2.mb-lg-0
        %li.nav-item
          %a.nav-link.active{"aria-current" => "page", :href => "#"} Home
        %li.nav-item
          %a.nav-link{:href => "#"} Link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
          %ul.dropdown-menu{"aria-labelledby" => "navbarDropdown"}
            %li
              %a.dropdown-item{:href => "#"} Action
            %li
              %a.dropdown-item{:href => "#"} Another action
            %li
              %hr.dropdown-divider/
            %li
              %a.dropdown-item{:href => "#"} Something else here
        %li.nav-item
          %a.nav-link.disabled Disabled
      %form.d-flex
        %input.form-control.me-2{"aria-label" => "Search", :placeholder => "Search", :type => "search"}/
        %button.btn.btn-outline-success{:type => "submit"} Search
.container-fluid
  %h1 Hello word
  = link_to "Private Policy",privacy_policy_path, class: 'btn btn-lg btn-warning'

app/views/static_pages/privacy_policy.html.haml
%h1 StaticPages#privacy_policy
%p Find me in app/views/static_pages/privacy_policy.html.erb
= link_to "Home",root_path